language: rust
sudo: true
rust:
    - 1.47.0

jobs:
  include:
    - stage: "Build"
      os: linux
      dist: bionic
      before_script:
        - ci/setup.sh || travis_terminate 1
      script:
        - ci/check.sh
        - ./build.sh || travis_terminate 1
        - export PATH="$PWD/target/debug:$PATH"
        - integration/integration.sh

    - stage: "Release"
      os: linux
      dist: bionic
      before_script:
         - export VERSION=$(grep '^version' packages/hurl/Cargo.toml | cut -f2 -d'"')
         - sudo apt install -y libcurl4-openssl-dev
      script:
         - ci/man.sh
         - ci/release.sh
         - ci/create_tarball.sh linux
         - ci/deb.sh
      deploy:
          provider: script
          script: ci/deploy.sh
          skip_cleanup: true
          on:
              all_branch: true
          tags: true

    - stage: "Release"
      os: osx
      before_script:
         - brew install jq
         - export VERSION=$(grep '^version' packages/hurl/Cargo.toml | cut -f2 -d'"')
      script:
         - ci/man.sh
         - ci/release.sh
         - ci/create_tarball.sh osx
      deploy:
          provider: script
          script: ci/deploy.sh
          skip_cleanup: true
          on:
              all_branch: true
          tags: true

