language: rust
sudo: true
rust:
    - 1.46.0

jobs:
  include:
    - stage: "Build"
      os: linux
      dist: bionic
      before_script:
        - ci/setup.sh
      script:
        - ci/check.sh
        - ./build.sh
        - export PATH="$PWD/target/debug:$PATH"
        - integration/integration.sh

    - stage: "Release"
      os: linux
      dist: bionic
      before_script:
         - export VERSION=$(grep '^version' Cargo.toml | cut -f2 -d'"')
         - sudo apt install libcurl4-openssl-dev
      script:
         - ci/man.sh
         - ci/release.sh
         - ci/create_tarball.sh linux
         - ci/deb.sh
      deploy:
          provider: script
          script: ci/deploy.sh
          skip_cleanup: true
          on:
              all_branch: true
          tags: true

    - stage: "Release"
      os: osx
      before_script:
         - export VERSION=$(grep '^version' Cargo.toml | cut -f2 -d'"')
      script:
         - ci/man.sh
         - ci/release.sh
         - ci/create_tarball.sh osx
      deploy:
          provider: script
          script: ci/deploy.sh
          skip_cleanup: true
          on:
              all_branch: true
          tags: true

