[package]
name = "hurlfmt"
version = "1.1.0"
authors = ["Fabrice Reix <fabrice.reix@orange.com>"]
edition = "2018"
license = "http://www.apache.org/licenses/LICENSE-2.0"
description = "format Hurl files"

[features]
# Treat warnings as a build error.
strict = []

[dependencies]
atty = "0.2.13"
clap = "2.33.0"
regex = "1.1.0"

[dependencies.hurl_core]
path = "../hurl_core"

[dev-dependencies]
proptest = "0.9.4"



