[package]
name = "hurlfmt"
version = "1.2.0"
authors = ["Fabrice Reix <fabrice.reix@orange.com>"]
edition = "2018"
license = "Apache-2.0"
description = "format Hurl files"
documentation = "https://hurl.dev"
homepage = "https://hurl.dev"
repository = "https://github.com/Orange-OpenSource/hurl"

[features]
# Treat warnings as a build error.
strict = []

[dependencies]
atty = "0.2.13"
clap = "2.33.0"
hurl_core = { version = "1.1.0", path = "../hurl_core" }
regex = "1.1.0"

[dev-dependencies]
proptest = "0.9.4"



