[package]
name = "hurl_core"
version = "1.2.0"
authors = ["Fabrice Reix <fabrice.reix@orange.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Hurl Core" 

[features]
# Treat warnings as a build error.
strict = []


[dependencies]
float-cmp = "0.6.0"
sxd-document = "0.3.2"


