[package]
name = "hurl_core"
version = "1.1.0"
authors = ["Fabrice Reix <fabrice.reix@orange.com>"]
edition = "2018"


[features]
# Treat warnings as a build error.
strict = []


[dependencies]
float-cmp = "0.6.0"
sxd-document = "0.3.2"


