name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install Flask && cd integration && python3 server.py &
      - run: wget https://snapshots.mitmproxy.org/5.2/mitmproxy-5.2-linux.tar.gz -O - | tar -xz && ./mitmdump -p 8888 --modify-header "/From-Proxy/Hello" &
      - name: Run build
        run: ./build.sh
      - name: Run integration tests
        run:  export PATH="$PWD/target/debug:$PATH" && integration/integration.sh

  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "mypath"
      - run:  echo VERSION=$(grep '^version' packages/hurl/Cargo.toml | cut -f2 -d'"') >> $GITHUB_ENV
      - run: ci/man.sh
      - run: ci/release.sh
      - run: ci/create_tarball.sh linux
      - run: ci/deb.sh
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          path: target/upload/*

  release-osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run:  echo VERSION=$(grep '^version' packages/hurl/Cargo.toml | cut -f2 -d'"') >> $GITHUB_ENV
      - run: ci/man.sh
      - run: ci/release.sh
      - run: ci/create_tarball.sh osx
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          path: target/upload/*
